### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by FabienCarmagnac** [Sebastiaan76/truefx-downloader#7] opened 2019-10-12 15:52 UTC
Executing (python37, win 10) :

python downloader.py -c EURUSD -y 2019 -m 01 myuser mypass

fails with error:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Python37\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Python37\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Python37\lib\ssl.py", line 853, in _create
    self.do_handshake()
  File "C:\Python37\lib\ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.truefx.com', port=443): Max retries exceeded with url: /?page=loginz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "downloader.py", line 97, in <module>
    dl.open_session()
  File "downloader.py", line 33, in open_session
    self.session.post('https://www.truefx.com/?page=loginz', data=payload)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python37\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.truefx.com', port=443): Max retries exceeded with url: /?page=loginz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)')))

**Comment by kingwongf** [comment] 2019-10-13 09:36
Second on this same issue. 
`requests.exceptions.SSLError: HTTPSConnectionPool(host='www.truefx.com', port=443): Max retries exceeded with url: /?page=loginz (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
`
Tried to redownload the gd_bundle-g2-g1.crt but still raises same error

**Comment by Sebastiaan76** [comment] 2019-11-21 02:47
Sorry for delay in getting to this. Will take a look and try to fix this issue.

EDIT: So, it looks like the True FX folks have completely re-written the site. This means I'll need to look at if/how I can re-factor the entire code to work with the new URL's. I'll try and take a look over the weekend at how much work this might entail.

**Comment by Sebastiaan76** [comment] 2020-03-31 11:35
looks like TrueFX is no longer free, or scrapable, so closing this as I'm not going to be able to do much. The Candle.py and Database.py scripts should still be useful in their own right though.

**Closed as completed by Sebastiaan76** 2020-03-31 11:35 UTC
